version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    expose:
      - '3000'
    env_file:
      - ./client/.env
    depends_on:
      - server

  server:
    build: ./server
    expose:
      - '5000'
    env_file:
      - ./server/.env

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '80:80'
    depends_on:
      - client
