version: '3'
services:
  client:
    build:
      context: client
      dockerfile: Dockerfile.dev
    expose:
      - '3000'
    env_file:
      - client/.env
    depends_on:
      - server

  server:
    build: server
    expose:
      - '5000'
    env_file:
      - server/.env

  nginx:
    image: nginx:1.25.2-alpine-slim
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - client
